
# definition used by magenta (models\music_vae\data.py)
MELODY_PROGRAMS = range(0, 32)  # piano, chromatic percussion, organ, guitar
BASS_PROGRAMS = range(32, 40)
ELECTRIC_BASS_PROGRAM = 33

MIN_MIDI_PITCH = 0
MAX_MIDI_PITCH = 127
MIDI_PITCHES = 128

PIANO_MIN_MIDI_PITCH = 21
PIANO_MAX_MIDI_PITCH = 108

MAX_INSTRUMENT_NUMBER = 127

STEPS_PER_QUARTER = 4
QUANTIZE_CUTOFF = 0.5

MELODY_NOTE_OFF = -1
MELODY_NO_EVENT = -2
MELODY_NUM_SPECIAL_EVENTS = 2

DEFAULT_NUMERATOR = 4
DEFAULT_DENOMINATOR = 4
DEFAULT_QPM = 120.
